### ISSUE TITLE
NoClassDefFoundError: com/googlecode/aviator/AviatorEvaluator

### ISSUE THREAD

**Issue by zhouyang2019** [RealtimeCompute/ververica-cep-demo#4]
Caused by: java.lang.NoClassDefFoundError: com/googlecode/aviator/AviatorEvaluator
	at org.apache.flink.cep.dynamic.condition.AviatorCondition.checkExpression(AviatorCondition.java:96) ~[flink-cep-1.15-vvr-6.0.4-SNAPSHOT.jar:1.15-vvr-6.0.4-SNAPSHOT]
	at org.apache.flink.cep.dynamic.condition.AviatorCondition.<init>(AviatorCondition.java:58) ~[flink-cep-1.15-vvr-6.0.4-SNAPSHOT.jar:1.15-vvr-6.0.4-SNAPSHOT]
	at org.apache.flink.cep.dynamic.condition.AviatorCondition.<init>(AviatorCondition.java:50) ~[flink-cep-1.15-vvr-6.0.4-SNAPSHOT.jar:1.15-vvr-6.0.4-SNAPSHOT]

	
pom.xml:
`<dependency>
            <groupId>com.googlecode.aviator</groupId>
            <artifactId>aviator</artifactId>
            <version>5.3.1</version>
        </dependency>
        <dependency>
            <groupId>com.alibaba.ververica</groupId>
            <artifactId>flink-cep</artifactId>
            <version>1.15-vvr-6.0.4</version>
            <scope>provided</scope>
        </dependency>`

**Comment by bgeng777** [comment]
Hi @zhouyang2019 , the flink-cep-1.15-vvr-6.0.4-SNAPSHOT.jar is not a fat jar and as a result, when you want to use AviatorCondition, you may have to add the aviator dependency in your job jar by yourself.

**Comment by wpcaishaoyu** [comment]
i already add AviatorCondition in the project，but not ok

**Comment by wpcaishaoyu** [comment]
这个是需要把AviatorCondition依赖打到这个，cep包里面，还是在项目打出来的包有就可以

**Comment by bgeng777** [comment]
> 这个是需要把AviatorCondition依赖打到这个，cep包里面，还是在项目打出来的包有就可以

需要打到作业jar里
